name: path_provider
description: Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
repository: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+path_provider%22
version: 2.0.8

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: path_provider_android
      ios:
        default_package: path_provider_ios
      macos:
        default_package: path_provider_macos
      linux:
        default_package: path_provider_linux
      windows:
        default_package: path_provider_windows

dependencies:
  flutter:
    sdk: flutter
  path_provider_android:
    git:
      url: https://github.com/rizalkotlin/path_provider_android.git
      ref: 4ed63aca86f63f4f63cafb50b0a6e03efb2e57de
  path_provider_ios:
    git:
      url: https://github.com/rizalkotlin/path_provider_ios.git
      ref: 082593837a39a203b079bd25665061d2ad73f429
  path_provider_linux:
    git:
      url: https://github.com/rizalkotlin/path_provider_linux.git
  path_provider_macos:
    git:
      url: https://github.com/rizalkotlin/path_provider_macos.git
  path_provider_platform_interface:
    git:
      url: https://github.com/rizalkotlin/path_provider_platform_interface.git
  path_provider_windows:
    git:
      url: https://github.com/rizalkotlin/path_provider_windows.git
      ref: 15857a89852c78d164768686de1b14ec368d0be6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.0
